<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="5.2.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenCMIS.Shared\OpenCMIS.Shared.csproj" />
    <ProjectReference Include="..\OpenCMIS.App.Core\OpenCMIS.App.Core.csproj" />
    <ProjectReference Include="..\OpenCMIS.Transport.I2C.Cypress\OpenCMIS.Transport.I2C.Cypress.csproj" />
    <ProjectReference Include="..\OpenCMIS.Transport.I2C.Serial\OpenCMIS.Transport.I2C.Serial.csproj" />
  </ItemGroup>
</Project>
