<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="OpenCMIS.CDB.Core.csproj.DotSettings" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenCMIS.Shared\OpenCMIS.Shared.csproj" />
    <ProjectReference Include="..\OpenCMIS.Protocol.Abstractions\OpenCMIS.Protocol.Abstractions.csproj" />
    <ProjectReference Include="..\OpenCMIS.CDB.Abstractions\OpenCMIS.CDB.Abstractions.csproj" />
  </ItemGroup>
</Project>
