<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0-preview.*" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenCMIS.Shared\OpenCMIS.Shared.csproj" />
    <ProjectReference Include="..\OpenCMIS.Transport.Abstractions\OpenCMIS.Transport.Abstractions.csproj" />
    <ProjectReference Include="..\OpenCMIS.Module.Core\OpenCMIS.Module.Core.csproj" />
    <ProjectReference Include="..\OpenCMIS.Transport.I2C\OpenCMIS.Transport.I2C.csproj" />
    <ProjectReference Include="..\OpenCMIS.Protocol.Abstractions\OpenCMIS.Protocol.Abstractions.csproj" />
    <ProjectReference Include="..\OpenCMIS.Protocol.Core\OpenCMIS.Protocol.Core.csproj" />
    <ProjectReference Include="..\OpenCMIS.CDB.Abstractions\OpenCMIS.CDB.Abstractions.csproj" />
    <ProjectReference Include="..\OpenCMIS.CDB.Core\OpenCMIS.CDB.Core.csproj" />
  </ItemGroup>
</Project>
